// <auto-generated />
using LeagueAPI.net6.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeagueAPI.net6.Migrations
{
    [DbContext(typeof(FootballDbContext))]
    [Migration("20220420190046_BothTeamsAddedToDatabase")]
    partial class BothTeamsAddedToDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LeagueAPI.net6.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            FirstName = "Doug",
                            LastName = "Dig",
                            Position = 0,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Vince",
                            LastName = "Van Douche",
                            Position = 1,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Tony",
                            LastName = "Poloni",
                            Position = 3,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Rahn",
                            LastName = "Barn",
                            Position = 3,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Clive",
                            LastName = "Deek",
                            Position = 2,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Cedric",
                            LastName = "Medric",
                            Position = 4,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Phil",
                            LastName = "Chill",
                            Position = 5,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Mike",
                            LastName = "Von Spike",
                            Position = 6,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "Kevin",
                            LastName = "Badger",
                            Position = 8,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "Steve",
                            LastName = "Badger",
                            Position = 9,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "Zack",
                            LastName = "Crack",
                            Position = 7,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 14,
                            FirstName = "Simon",
                            LastName = "Snada",
                            Position = 0,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 15,
                            FirstName = "Joe",
                            LastName = "Johnson",
                            Position = 1,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 16,
                            FirstName = "Cliff",
                            LastName = "Richards",
                            Position = 3,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 17,
                            FirstName = "Peter",
                            LastName = "Perkins",
                            Position = 3,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 18,
                            FirstName = "Jay",
                            LastName = "Yay",
                            Position = 2,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 19,
                            FirstName = "Mel",
                            LastName = "Dean",
                            Position = 4,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 20,
                            FirstName = "Mike",
                            LastName = "Hawkins",
                            Position = 5,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 21,
                            FirstName = "Grant",
                            LastName = "Taylor",
                            Position = 6,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 22,
                            FirstName = "Phil",
                            LastName = "Smith",
                            Position = 7,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 23,
                            FirstName = "Thomas",
                            LastName = "Vindel",
                            Position = 8,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 24,
                            FirstName = "Darren",
                            LastName = "Parker",
                            Position = 9,
                            TeamId = 2
                        });
                });

            modelBuilder.Entity("LeagueAPI.net6.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Manager")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stadium")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Manager = "Tommy Turtle",
                            Name = "Tortoise Town",
                            Stadium = "Shell Stadium"
                        },
                        new
                        {
                            Id = 2,
                            Manager = "Cyril Sneer",
                            Name = "Bongo United",
                            Stadium = "Stadium of Dark"
                        });
                });

            modelBuilder.Entity("LeagueAPI.net6.Models.Player", b =>
                {
                    b.HasOne("LeagueAPI.net6.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("LeagueAPI.net6.Models.Team", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
